#!/bin/sh
# Minimal Gradle wrapper script — generated by `gradle wrapper`.
# Real wrapper jar lives in gradle/wrapper/gradle-wrapper.jar; place it
# alongside this script in your checkout.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
APP_HOME=$(cd "$(dirname "$0")" && pwd)
exec java $DEFAULT_JVM_OPTS -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "$@"